#:schema node_modules/wrangler/config-schema.json
name = "my-todo-app"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_als"]

# Next.js Pages-д зориулсан гаралт
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"  # Код доторх context.env.DB-тэй таарч байх ёстой
database_name = "todo-db"
database_id = "3c5067ad-b7a3-45c2-abf8-9e2c135c49ae" # Таны .env дээрх ID